### ISSUE TITLE
Failed to load audio

### ISSUE THREAD

**Issue by darkfrog26** [dsymbol/decipher#10]
I'm trying to generate an SRT file for a video but I get the following error:
```
RuntimeError: Failed to load audio: ffmpeg version 5.1.1-1ubuntu1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12 (Ubuntu 12.2.0-1ubuntu1)
  configuration: --prefix=/usr --extra-version=1ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[aac @ 0x55f18b9979c0] Format aac detected only with low score of 1, misdetection possible!
chuck.s01e02.bluray.1080p.DD5.1.H265-d3g.aac: End of file
```
Not really sure why. To be clear, I can watch the video without any trouble with audio.

**Comment by darkfrog26** [comment]
FYI, here's the ffprobe output:
```
ffprobe version 5.1.1-1ubuntu1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12 (Ubuntu 12.2.0-1ubuntu1)
  configuration: --prefix=/usr --extra-version=1ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, srt, from 'chuck.s01e02.bluray.1080p.DD5.1.H265-d3g.srt':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Subtitle: subrip
```
after converting the format to mp4 everything worked fine

**Comment by dsymbol** [comment]
What was the format before you converted it to mp4?

**Comment by darkfrog26** [comment]
Sorry, just realized I didn't send the correct ffprobe. This is the details of the video before I converted it to mp4:
```
Input #0, matroska,webm, from 'chuck.s01e02.bluray.1080p.DD5.1.H265-d3g.mkv':
  Metadata:
    title           : chuck.s01e02.bluray.1080p.DD5.1.H265-d3g
    encoder         : libebml v1.3.4 + libmatroska v1.4.5
    creation_time   : 2018-03-14T23:26:20.000000Z
  Duration: 00:42:50.53, start: 0.000000, bitrate: 3275 kb/s
  Stream #0:0: Video: hevc (Main), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS             : 2825999
      BPS-eng         : 2825999
      DURATION        : 00:42:49.567000000
      DURATION-eng    : 00:42:49.567000000
      NUMBER_OF_FRAMES: 61608
      NUMBER_OF_FRAMES-eng: 61608
      NUMBER_OF_BYTES : 907699354
      NUMBER_OF_BYTES-eng: 907699354
      _STATISTICS_WRITING_APP: DVDFab 10.0.8.7
      _STATISTICS_WRITING_APP-eng: DVDFab 10.0.8.7
      _STATISTICS_WRITING_DATE_UTC: 2018-03-14 23:26:20
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-03-14 23:26:20
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s (default)
    Metadata:
      BPS             : 448000
      BPS-eng         : 448000
      DURATION        : 00:42:50.528000000
      DURATION-eng    : 00:42:50.528000000
      NUMBER_OF_FRAMES: 80329
      NUMBER_OF_FRAMES-eng: 80329
      NUMBER_OF_BYTES : 143949568
      NUMBER_OF_BYTES-eng: 143949568
      _STATISTICS_WRITING_APP: DVDFab 10.0.8.7
      _STATISTICS_WRITING_APP-eng: DVDFab 10.0.8.7
      _STATISTICS_WRITING_DATE_UTC: 2018-03-14 23:26:20
      _STATISTICS_WRITING_DATE_UTC-eng: 2018-03-14 23:26:20
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

**Comment by dsymbol** [comment]
Could you try this [file](https://github.com/ietf-wg-cellar/matroska-test-files/blob/master/test_files/test2.mkv) and tell me if it works, I believe the problem is specific to that file as I can't reproduce it.

**Comment by darkfrog26** [comment]
I get the same error:
```
python3 -m decipher transcribe -i test2.mkv --model small                    ✔ │ mhicks@fileserver │ 17:30:14 
Converting test2.mkv to test2.aac...
/home/mhicks/Downloads/test2.mkv: Invalid data found when processing input
Traceback (most recent call last):
  File "/home/mhicks/.local/lib/python3.10/site-packages/whisper/audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
  File "/home/mhicks/.local/lib/python3.10/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```

**Comment by dsymbol** [comment]
Ran the exact command on the same file on Windows and Kubuntu with no problems whatsoever,
Consider purging ffmpeg from your system and trying to use [this](https://github.com/imageio/imageio-binaries/blob/master/ffmpeg/ffmpeg-linux64-v4.1) one instead add it to path before running decipher.

**Comment by darkfrog26** [comment]
Unfortunately, I seem to be getting the same error:
```
> python3 -m decipher transcribe -i chuck.s01e02.bluray.1080p.DD5.1.H265-d3g.mkv --model small 
Converting chuck.s01e02.bluray.1080p.DD5.1.H265-d3g.mkv to chuck.s01e02.bluray.1080p.DD5.1.H265-d3g.aac...
    Last message repeated 1 times
Traceback (most recent call last):
  File "/home/mhicks/.local/lib/python3.10/site-packages/whisper/audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
  File "/home/mhicks/.local/lib/python3.10/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mhicks/.local/lib/python3.10/site-packages/decipher/__main__.py", line 57, in <module>
    sys.exit(main())
  File "/home/mhicks/.local/lib/python3.10/site-packages/decipher/__main__.py", line 53, in main
    cli()
  File "/home/mhicks/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mhicks/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mhicks/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mhicks/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mhicks/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/mhicks/.local/lib/python3.10/site-packages/decipher/__main__.py", line 27, in _transcribe_cli
    transcribe(
  File "/home/mhicks/.local/lib/python3.10/site-packages/decipher/action.py", line 26, in transcribe
    result = model.transcribe(audio_file, task=task, language=language, verbose=True, fp16=gpu)
  File "/home/mhicks/.local/lib/python3.10/site-packages/whisper/transcribe.py", line 84, in transcribe
    mel = log_mel_spectrogram(audio)
  File "/home/mhicks/.local/lib/python3.10/site-packages/whisper/audio.py", line 111, in log_mel_spectrogram
    audio = load_audio(audio)
  File "/home/mhicks/.local/lib/python3.10/site-packages/whisper/audio.py", line 47, in load_audio
    raise RuntimeError(f"Failed to load audio: {e.stderr.decode()}") from e
RuntimeError: Failed to load audio: ffmpeg version 4.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[aac @ 0x563dc80] Format aac detected only with low score of 1, misdetection possible!
chuck.s01e02.bluray.1080p.DD5.1.H265-d3g.aac: Invalid data found when processing input
```

**Comment by darkfrog26** [comment]
Similarly failed with test2.mkv:
```
Converting test2.mkv to test2.aac...
/home/mhicks/Downloads/test2.mkv: Invalid data found when processing input
Traceback (most recent call last):
  File "/home/mhicks/.local/lib/python3.10/site-packages/whisper/audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
  File "/home/mhicks/.local/lib/python3.10/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mhicks/.local/lib/python3.10/site-packages/decipher/__main__.py", line 57, in <module>
    sys.exit(main())
  File "/home/mhicks/.local/lib/python3.10/site-packages/decipher/__main__.py", line 53, in main
    cli()
  File "/home/mhicks/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mhicks/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mhicks/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mhicks/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mhicks/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/mhicks/.local/lib/python3.10/site-packages/decipher/__main__.py", line 27, in _transcribe_cli
    transcribe(
  File "/home/mhicks/.local/lib/python3.10/site-packages/decipher/action.py", line 26, in transcribe
    result = model.transcribe(audio_file, task=task, language=language, verbose=True, fp16=gpu)
  File "/home/mhicks/.local/lib/python3.10/site-packages/whisper/transcribe.py", line 84, in transcribe
    mel = log_mel_spectrogram(audio)
  File "/home/mhicks/.local/lib/python3.10/site-packages/whisper/audio.py", line 111, in log_mel_spectrogram
    audio = load_audio(audio)
  File "/home/mhicks/.local/lib/python3.10/site-packages/whisper/audio.py", line 47, in load_audio
    raise RuntimeError(f"Failed to load audio: {e.stderr.decode()}") from e
RuntimeError: Failed to load audio: ffmpeg version 4.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
test2.aac: No such file or directory
```

**Comment by dsymbol** [comment]
Can you try using another computer/vm perhaps?

**Comment by darkfrog26** [comment]
I specifically need it on this server. It's running the latest version of Ubuntu with nothing extra special about it. I'm surprised this hasn't come up before.

**Comment by dsymbol** [comment]
Tried running it on latest Ubuntu using test2.mkv with no errors whatsoever. I'm unsure how I can help at this point seems to be a ffmpeg problem that's exclusive to your server..

**Comment by darkfrog26** [comment]
Thanks, I'll do some additional testing and see if I can figure out the problem.

**Comment by ProFire** [comment]
I'm also facing the same issue, but not on every file though.

I'm on Ubuntu 23.04, running ffmpeg 5.1.2.
