### ISSUE TITLE
SRT File wasn't created

### ISSUE THREAD

**Issue by Mage-Enderman** [dsymbol/decipher#18]
AppData\Local\Programs\Python\Python310\lib\site-packages\whisper\timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.

**Comment by Mage-Enderman** [comment]
Traceback (most recent call last):
  File "C:\Users\Mage\AppData\Local\Programs\Python\Python310\Scripts\decipher-script.py", line 33, in <module>
    sys.exit(load_entry_point('decipher==0.0.0', 'console_scripts', 'decipher')())
  File "C:\Users\Mage\AppData\Local\Programs\Python\Python310\lib\site-packages\decipher\__main__.py", line 53, in main
    cli()
  File "C:\Users\Mage\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Mage\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Mage\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Mage\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Mage\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Mage\AppData\Local\Programs\Python\Python310\lib\site-packages\decipher\__main__.py", line 27, in _transcribe_cli
    transcribe(
  File "C:\Users\Mage\AppData\Local\Programs\Python\Python310\lib\site-packages\decipher\action.py", line 32, in transcribe
    assert os.path.exists(srt_file), f"SRT file not generated?"
AssertionError: SRT file not generated?

**Comment by dsymbol** [comment]
What is the full name including extension of the video file you were trying to transcribe?

**Comment by Mage-Enderman** [comment]
"I Miss Old VR....mp4"

**Comment by Mage-Enderman** [comment]
It made the transcription with no issue. just didn't save it to an srt file or seemingly any file

**Comment by dsymbol** [comment]
fixed #16 [93956d1](https://github.com/dsymbol/decipher/commit/93956d19fd011ee324fbd39ca5978ed85dd41747)
