### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by View-my-Git-Lab-krafi** [dsymbol/decipher#28]
```
decipher gui
Traceback (most recent call last):
  File "C:\Users\krafi\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\krafi\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\krafi\AppData\Local\Programs\Python\Python39\Scripts\decipher.exe\__main__.py", line 4, in <module>
  File "C:\Users\krafi\AppData\Local\Programs\Python\Python39\lib\site-packages\decipher\__main__.py", line 4, in <module>
    from decipher.action import subtitle, transcribe
  File "C:\Users\krafi\AppData\Local\Programs\Python\Python39\lib\site-packages\decipher\action.py", line 10, in <module>
    from ffutils import ffprog
  File "C:\Users\krafi\AppData\Local\Programs\Python\Python39\lib\site-packages\ffutils\__init__.py", line 1, in <module>
    from .ff import get_ffmpeg_exe, ffprog
  File "C:\Users\krafi\AppData\Local\Programs\Python\Python39\lib\site-packages\ffutils\ff.py", line 116, in <module>
    def _download_exe(url: str, filename: str | Path) -> str:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

PS C:\Users\krafi\decipher>
```

PS C:\Users\krafi\decipher> python -m decipher gui
Traceback (most recent call last):
  File "C:\Users\krafi\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\krafi\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\krafi\decipher\decipher\__main__.py", line 4, in <module>
    from decipher.action import subtitle, transcribe
  File "C:\Users\krafi\decipher\decipher\action.py", line 10, in <module>
    from ffutils import ffprog
  File "C:\Users\krafi\AppData\Local\Programs\Python\Python39\lib\site-packages\ffutils\__init__.py", line 1, in <module>
    from .ff import get_ffmpeg_exe, ffprog
  File "C:\Users\krafi\AppData\Local\Programs\Python\Python39\lib\site-packages\ffutils\ff.py", line 116, in <module>
    def _download_exe(url: str, filename: str | Path) -> str:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by krafi-code** [comment]
https://gitlab.com/krafi/whispersub

same kind of project using pyside, just the diffrence is hardcode with sub process

**Comment by dsymbol** [comment]
If you're using a version of Python earlier than 3.10, you'll get a TypeError because that syntax is not supported.
