### ISSUE TITLE
Google Colab Issue

### ISSUE THREAD

**Issue by GingerMeadows** [dsymbol/decipher#31]
Hello! I tried running the Google Colab notebook, but I got this error: 

ValueError: Could not find the operator torchvision::nms. Please make sure you have already registered the operator and (if registered from C++) loaded it via torch.ops.load_library.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/decipher/__main__.py", line 4, in <module>
    from decipher.action import subtitle, transcribe
  File "/usr/local/lib/python3.10/dist-packages/decipher/action.py", line 7, in <module>
    from transformers import pipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1557, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1569, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
Could not find the operator torchvision::nms. Please make sure you have already registered the operator and (if registered from C++) loaded it via torch.ops.load_library.

**Comment by dsymbol** [comment]
Couldn't reproduce, can you try again?

**Comment by GingerMeadows** [comment]
Sorry for the late response! I tried again, and I got no error. It seems to have been solved by itself!
